server {
    listen 80;
    listen [::]:80;
    server_name quizzine.org www.quizzine.org;
    return 301 https://quizzine.org$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name quizzine.org www.quizzine.org;

    root /var/www/quizzine;
    index index.html;

    ssl_certificate /etc/nginx/ssl/quizzine.org.pem;
    ssl_certificate_key /etc/nginx/ssl/quizzine.org.key;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|pdf|pptx)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
