server {
    listen 80;
    listen [::]:80;
    server_name quizzine.org www.quizzine.org;

    root /var/www/quizzine;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|pdf|pptx)$ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
